name: example
description: An example app for frino_icons package.
publish: none

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  frino_icons:
    path: ../


flutter:
  uses-material-design: true

