name: frino_icons
description: The Frino Icon pack available as Flutter Icons. Provides 300+ additional icons to use in your apps.
version: 1.0.1+4
repository: https://github.com/clean/frino_icons

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  fonts:
    - family: FrinoIcons
      fonts:
        - asset: lib/fonts/FrinoIcons.ttf
          weight: 400
